#!/usr/bin/env bash
# =============================================================================
# sync-env.sh — Generate per-app .env.local from root .env
# =============================================================================
# Usage: ./scripts/sync-env.sh
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

GREEN='\033[0;32m'; BLUE='\033[0;34m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { echo -e "  ${GREEN}✓${NC} $1"; }

if [ ! -f "$ENV_FILE" ]; then
  echo -e "${RED}Error: .env not found. Copy .env.example to .env and fill in values.${NC}"
  exit 1
fi

set -a; source "$ENV_FILE"; set +a

DOMAIN="${DOMAIN:-nmrk.jayd.ai}"
BASE="https://$DOMAIN"

echo -e "\n${BLUE}━━━ Syncing environment for VM deployment ━━━${NC}\n"
echo "  Domain: $DOMAIN"
echo "  Tenant: ${AZURE_TENANT_ID:-NOT SET}"

# All apps share one Client ID (single domain = single origin)
CLIENT_ID="${AZURE_CLIENT_ID:-}"

write_env() {
  local app_dir="$1"
  shift
  local env_file="$REPO_ROOT/apps/$app_dir/.env.local"
  {
    echo "# Auto-generated by sync-env.sh — do not edit"
    echo "NEXT_PUBLIC_AZURE_CLIENT_ID=$CLIENT_ID"
    echo "NEXT_PUBLIC_AZURE_TENANT_ID=${AZURE_TENANT_ID:-}"
    for extra in "$@"; do
      [ -n "$extra" ] && echo "$extra"
    done
  } > "$env_file"
  ok "$app_dir"
}

echo -e "\n${BLUE}Apps:${NC}"

write_env "D00_hub" \
  "NEXT_PUBLIC_URL_DASHBOARD=$BASE/dashboard" \
  "NEXT_PUBLIC_URL_COMMERCIALISATION=$BASE/commercialisation" \
  "NEXT_PUBLIC_URL_TRANSACTIONS=$BASE/transactions" \
  "NEXT_PUBLIC_URL_OFFRE_RETAIL=$BASE/offre-retail" \
  "NEXT_PUBLIC_URL_VISITES=$BASE/visites" \
  "NEXT_PUBLIC_URL_COMPARABLES=$BASE/comparables" \
  "NEXT_PUBLIC_URL_PROPRIETAIRE=$BASE/proprietaire" \
  "NEXT_PUBLIC_GRAPHISTES_TIMESHEET_URL=$BASE/graphistes" \
  "NEXT_PUBLIC_ENCARTS_DIFFUSION_URL=$BASE/encarts"

write_env "D08-CU6_dashboard-offres"
write_env "D09-CU5_carte-commercialisation" "NEXT_PUBLIC_HUB_URL=$BASE"
write_env "D09-CU5_carte-transactions"      "NEXT_PUBLIC_HUB_URL=$BASE"
write_env "D05-CU1_carte-offre-retail"      "NEXT_PUBLIC_HUB_URL=$BASE"
write_env "D04-CU6_planning-visites"        "NEXT_PUBLIC_HUB_URL=$BASE"
write_env "D09-CU8_comparables"
write_env "D08-CU1_encarts-diffusion"
write_env "D06-CU8_feuilles-temps-graphistes"

echo -e "\n${GREEN}Done.${NC}"
